name: ultrasound
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8.*
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio 
  - pytorch::pytorch-cuda=11.6
  - opencv
  - ipykernel
  - tqdm
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - libstdcxx-ng
  - ipywidgets