name: ultrasound2
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8.*
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::torchaudio=0.13.1
  - pytorch::pytorch-cuda=11.6
  - opencv
  - ipykernel
  - tqdm
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - ipywidgets