name: ultrasound
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.8.*
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio 
  - pytorch::pytorch-cuda=11.6
  - opencv
  - ipykernel
  - tqdm
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - ipywidgets
  # You may need to uncomment out the following if you have issues with linux and you
  # see an error upon some python import like `ImportError: ... version `GLIBCXX_3.4.30' not found ...`
  # - libstdcxx-ng