#!/bin/bash
# This script is a simple wrapper to submit a job via `sbatch` and making sure that it emails you on any event
# of interest (e.g. when the job is submitted, when it starts, ends, crashes, etc.)
# This depends on you setting the environment variable SLURM_EMAIL_ADDRESS. You can do this in your ~/.bashrc.
#     export SLURM_EMAIL_ADDRESS=<me@my.com>
# Don't actually include the "<>" when you do this
#
# So you can more easily use this anywhere on M3, you can copy it to your PATH. I believe ~/bin should be in your PATH
# already. First, make sure that directory exists
#     mkdir ~/bin
# Then just copy this script into it
#     cp submit_job ~/bin
#
# Let Lex know if you don't want to receive *all* of the emails you get by default

sbatch --mail-type=ALL --mail-user=$SLURM_EMAIL_ADDRESS --chdir=$MY_ULTRASOUND_DIR $1
