#!/bin/bash
# This lets you watch the output of a Slurm job live, as if it was running in 
# your terminal. 
#
# You can optionally provide a job ID to look out for. Note that the output file
# does not immediately come into existence, so double-check that it exists if
# this command fails!
#
# If you don't specify a job ID, this will fallback to the latest job output file
# it finds.

OUTDIR=output/slurm

# See if user provided job id. If not, then fallback to latest job output file
if [ -z "$1" ]
  then
    JOB_FILE=$(ls -1 ${OUTDIR} | tail -n 1)
    echo "No job ID provided. Falling back to latest output file found in ${OUTDIR}"
else
  JOB_FILE=$(ls -1 ${OUTDIR} | grep $1)
fi

JOB_OUTPUT=$OUTDIR/$JOB_FILE

echo "Tailing ${JOB_OUTPUT}..."
echo
tail -f $JOB_OUTPUT
