#!/bin/bash
# This simply shows you a live version of the output of `show_job`.
#
# Just press Ctrl+C when you want to stop watching.
#
# You can optionally provide a job id as an argument, in which case it will only show
# details about that particular job.
#
# See M3's docs for info on the show_job command: https://docs.massive.org.au/M3/slurm/check-job-status.html

watch -n 1 --color show_job $1
