project:
  type: website

website:
  title: "MDN x Global MedEd"
  navbar:
    right:
      - about.qmd
      - icon: github
        text: Github
        href: https://github.com/DeepNeuron-AI/dynamic
      - text: Monash DeepNeuron
        href: https://www.deepneuron.org/
      - text: Global MedEd
        href: https://www.globalmeded.com.au/
format:
  html:
    theme: cosmo
    css: styles.css



